<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VICTORs-MacBook-Pro.local" failures="1" tests="3" name="Command line test" time="0.854" errors="0" timestamp="2021-10-23T20:30:43 PET">
  <testcase classname="asistente.AppTest" name="main" time="0.214"/>
  <testcase classname="asistente.OliverTest" name="prueba" time="0.023"/>
  <testcase classname="asistente.OliverTest" name="prueba2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at asistente.OliverTest.prueba2(OliverTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- prueba2 -->
</testsuite> <!-- Command line test -->
